export const TOGGLE_DONE_STATUS_CARD = "/card/TOGGLE-DONE-STATUS-CARD",
  TOGGLE_VISIBLE_CARD = "/card/TOGGLE-VISIBLE-CARD",
  ADD_CARD = "/card/ADD-CARD",
  DELETE_CARD = "/card/DELETE-CARD",
  START_EDIT_CARD = "/card/START-EDIT-CARD",
  SUBMIT_EDIT_CARD = "/card/SUBMIT-EDIT-CARD",
  HIDE_CARD = "/card/HIDE-CARD",
  SHOW_CARD = "/card/SHOW-CARD";
